version: '3.8'

services:
  app:
    build: .
    container_name: myapp-backend
#    env_file:
#      - .env
    expose:
      - "8080"

  nginx:
    image: nginx:alpine
    container_name: myapp-nginx
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app

  db:
    image: mysql:8
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
#      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
